//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInmobiliaria.SOAPServices.Tests.ProformaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proforma", Namespace="http://schemas.datacontract.org/2004/07/GestionInmobiliaria.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class Proforma : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecproformaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProformaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdunidadinmobiliariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IgvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionInmobiliaria.SOAPServices.Tests.ProformaWS.UnidadInmobiliaria UnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idmonedaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecproforma {
            get {
                return this.FecproformaField;
            }
            set {
                if ((this.FecproformaField.Equals(value) != true)) {
                    this.FecproformaField = value;
                    this.RaisePropertyChanged("Fecproforma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProforma {
            get {
                return this.IdProformaField;
            }
            set {
                if ((this.IdProformaField.Equals(value) != true)) {
                    this.IdProformaField = value;
                    this.RaisePropertyChanged("IdProforma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idunidadinmobiliaria {
            get {
                return this.IdunidadinmobiliariaField;
            }
            set {
                if ((this.IdunidadinmobiliariaField.Equals(value) != true)) {
                    this.IdunidadinmobiliariaField = value;
                    this.RaisePropertyChanged("Idunidadinmobiliaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Igv {
            get {
                return this.IgvField;
            }
            set {
                if ((this.IgvField.Equals(value) != true)) {
                    this.IgvField = value;
                    this.RaisePropertyChanged("Igv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subotal {
            get {
                return this.SubotalField;
            }
            set {
                if ((this.SubotalField.Equals(value) != true)) {
                    this.SubotalField = value;
                    this.RaisePropertyChanged("Subotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionInmobiliaria.SOAPServices.Tests.ProformaWS.UnidadInmobiliaria Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idmoneda {
            get {
                return this.idmonedaField;
            }
            set {
                if ((this.idmonedaField.Equals(value) != true)) {
                    this.idmonedaField = value;
                    this.RaisePropertyChanged("idmoneda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadInmobiliaria", Namespace="http://schemas.datacontract.org/2004/07/GestionInmobiliaria.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class UnidadInmobiliaria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AreaConstruidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AreaJardinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AreaLibreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AreaTechadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AreaTerrazaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AreaTerrenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BonoTPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Edificio EdificioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoInmuebleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Etapa EtapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FichaIndependizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCargaStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEdificioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEtapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoInmuebleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroInmuebleActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroInmuebleOriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroPisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NumBaniosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NumDormitorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioListaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Proyecto ProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionInmobiliaria.SOAPServices.Tests.ProformaWS.TipoInmueble TipoInmuebleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anulado {
            get {
                return this.AnuladoField;
            }
            set {
                if ((this.AnuladoField.Equals(value) != true)) {
                    this.AnuladoField = value;
                    this.RaisePropertyChanged("Anulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AreaConstruida {
            get {
                return this.AreaConstruidaField;
            }
            set {
                if ((this.AreaConstruidaField.Equals(value) != true)) {
                    this.AreaConstruidaField = value;
                    this.RaisePropertyChanged("AreaConstruida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AreaJardin {
            get {
                return this.AreaJardinField;
            }
            set {
                if ((this.AreaJardinField.Equals(value) != true)) {
                    this.AreaJardinField = value;
                    this.RaisePropertyChanged("AreaJardin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AreaLibre {
            get {
                return this.AreaLibreField;
            }
            set {
                if ((this.AreaLibreField.Equals(value) != true)) {
                    this.AreaLibreField = value;
                    this.RaisePropertyChanged("AreaLibre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AreaTechada {
            get {
                return this.AreaTechadaField;
            }
            set {
                if ((this.AreaTechadaField.Equals(value) != true)) {
                    this.AreaTechadaField = value;
                    this.RaisePropertyChanged("AreaTechada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AreaTerraza {
            get {
                return this.AreaTerrazaField;
            }
            set {
                if ((this.AreaTerrazaField.Equals(value) != true)) {
                    this.AreaTerrazaField = value;
                    this.RaisePropertyChanged("AreaTerraza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AreaTerreno {
            get {
                return this.AreaTerrenoField;
            }
            set {
                if ((this.AreaTerrenoField.Equals(value) != true)) {
                    this.AreaTerrenoField = value;
                    this.RaisePropertyChanged("AreaTerreno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BonoTP {
            get {
                return this.BonoTPField;
            }
            set {
                if ((this.BonoTPField.Equals(value) != true)) {
                    this.BonoTPField = value;
                    this.RaisePropertyChanged("BonoTP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Edificio Edificio {
            get {
                return this.EdificioField;
            }
            set {
                if ((object.ReferenceEquals(this.EdificioField, value) != true)) {
                    this.EdificioField = value;
                    this.RaisePropertyChanged("Edificio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoInmueble {
            get {
                return this.EstadoInmuebleField;
            }
            set {
                if ((this.EstadoInmuebleField.Equals(value) != true)) {
                    this.EstadoInmuebleField = value;
                    this.RaisePropertyChanged("EstadoInmueble");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Etapa Etapa {
            get {
                return this.EtapaField;
            }
            set {
                if ((object.ReferenceEquals(this.EtapaField, value) != true)) {
                    this.EtapaField = value;
                    this.RaisePropertyChanged("Etapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FichaIndependizacion {
            get {
                return this.FichaIndependizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FichaIndependizacionField, value) != true)) {
                    this.FichaIndependizacionField = value;
                    this.RaisePropertyChanged("FichaIndependizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCargaStock {
            get {
                return this.IdCargaStockField;
            }
            set {
                if ((this.IdCargaStockField.Equals(value) != true)) {
                    this.IdCargaStockField = value;
                    this.RaisePropertyChanged("IdCargaStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEdificio {
            get {
                return this.IdEdificioField;
            }
            set {
                if ((this.IdEdificioField.Equals(value) != true)) {
                    this.IdEdificioField = value;
                    this.RaisePropertyChanged("IdEdificio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEtapa {
            get {
                return this.IdEtapaField;
            }
            set {
                if ((this.IdEtapaField.Equals(value) != true)) {
                    this.IdEtapaField = value;
                    this.RaisePropertyChanged("IdEtapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMoneda {
            get {
                return this.IdMonedaField;
            }
            set {
                if ((this.IdMonedaField.Equals(value) != true)) {
                    this.IdMonedaField = value;
                    this.RaisePropertyChanged("IdMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProyecto {
            get {
                return this.IdProyectoField;
            }
            set {
                if ((this.IdProyectoField.Equals(value) != true)) {
                    this.IdProyectoField = value;
                    this.RaisePropertyChanged("IdProyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoInmueble {
            get {
                return this.IdTipoInmuebleField;
            }
            set {
                if ((this.IdTipoInmuebleField.Equals(value) != true)) {
                    this.IdTipoInmuebleField = value;
                    this.RaisePropertyChanged("IdTipoInmueble");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVista {
            get {
                return this.IdVistaField;
            }
            set {
                if ((this.IdVistaField.Equals(value) != true)) {
                    this.IdVistaField = value;
                    this.RaisePropertyChanged("IdVista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroInmuebleActual {
            get {
                return this.NroInmuebleActualField;
            }
            set {
                if ((object.ReferenceEquals(this.NroInmuebleActualField, value) != true)) {
                    this.NroInmuebleActualField = value;
                    this.RaisePropertyChanged("NroInmuebleActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroInmuebleOriginal {
            get {
                return this.NroInmuebleOriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.NroInmuebleOriginalField, value) != true)) {
                    this.NroInmuebleOriginalField = value;
                    this.RaisePropertyChanged("NroInmuebleOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroPiso {
            get {
                return this.NroPisoField;
            }
            set {
                if ((this.NroPisoField.Equals(value) != true)) {
                    this.NroPisoField = value;
                    this.RaisePropertyChanged("NroPiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NumBanios {
            get {
                return this.NumBaniosField;
            }
            set {
                if ((this.NumBaniosField.Equals(value) != true)) {
                    this.NumBaniosField = value;
                    this.RaisePropertyChanged("NumBanios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NumDormitorio {
            get {
                return this.NumDormitorioField;
            }
            set {
                if ((this.NumDormitorioField.Equals(value) != true)) {
                    this.NumDormitorioField = value;
                    this.RaisePropertyChanged("NumDormitorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCertificado {
            get {
                return this.NumeroCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCertificadoField, value) != true)) {
                    this.NumeroCertificadoField = value;
                    this.RaisePropertyChanged("NumeroCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioBase {
            get {
                return this.PrecioBaseField;
            }
            set {
                if ((this.PrecioBaseField.Equals(value) != true)) {
                    this.PrecioBaseField = value;
                    this.RaisePropertyChanged("PrecioBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioLista {
            get {
                return this.PrecioListaField;
            }
            set {
                if ((this.PrecioListaField.Equals(value) != true)) {
                    this.PrecioListaField = value;
                    this.RaisePropertyChanged("PrecioLista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioVenta {
            get {
                return this.PrecioVentaField;
            }
            set {
                if ((this.PrecioVentaField.Equals(value) != true)) {
                    this.PrecioVentaField = value;
                    this.RaisePropertyChanged("PrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Proyecto Proyecto {
            get {
                return this.ProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProyectoField, value) != true)) {
                    this.ProyectoField = value;
                    this.RaisePropertyChanged("Proyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionInmobiliaria.SOAPServices.Tests.ProformaWS.TipoInmueble TipoInmueble {
            get {
                return this.TipoInmuebleField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoInmuebleField, value) != true)) {
                    this.TipoInmuebleField = value;
                    this.RaisePropertyChanged("TipoInmueble");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Edificio", Namespace="http://schemas.datacontract.org/2004/07/GestionInmobiliaria.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class Edificio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AreaTerrenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoEdificioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Etapa EtapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoConstruccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPisosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroUnidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anulado {
            get {
                return this.AnuladoField;
            }
            set {
                if ((this.AnuladoField.Equals(value) != true)) {
                    this.AnuladoField = value;
                    this.RaisePropertyChanged("Anulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AreaTerreno {
            get {
                return this.AreaTerrenoField;
            }
            set {
                if ((this.AreaTerrenoField.Equals(value) != true)) {
                    this.AreaTerrenoField = value;
                    this.RaisePropertyChanged("AreaTerreno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoEdificio {
            get {
                return this.EstadoEdificioField;
            }
            set {
                if ((this.EstadoEdificioField.Equals(value) != true)) {
                    this.EstadoEdificioField = value;
                    this.RaisePropertyChanged("EstadoEdificio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Etapa Etapa {
            get {
                return this.EtapaField;
            }
            set {
                if ((object.ReferenceEquals(this.EtapaField, value) != true)) {
                    this.EtapaField = value;
                    this.RaisePropertyChanged("Etapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoConstruccion {
            get {
                return this.IdTipoConstruccionField;
            }
            set {
                if ((this.IdTipoConstruccionField.Equals(value) != true)) {
                    this.IdTipoConstruccionField = value;
                    this.RaisePropertyChanged("IdTipoConstruccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPisos {
            get {
                return this.NumeroPisosField;
            }
            set {
                if ((this.NumeroPisosField.Equals(value) != true)) {
                    this.NumeroPisosField = value;
                    this.RaisePropertyChanged("NumeroPisos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroUnidades {
            get {
                return this.NumeroUnidadesField;
            }
            set {
                if ((this.NumeroUnidadesField.Equals(value) != true)) {
                    this.NumeroUnidadesField = value;
                    this.RaisePropertyChanged("NumeroUnidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Etapa", Namespace="http://schemas.datacontract.org/2004/07/GestionInmobiliaria.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class Etapa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroEdificiosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroInmueblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Proyecto ProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroEdificios {
            get {
                return this.NumeroEdificiosField;
            }
            set {
                if ((this.NumeroEdificiosField.Equals(value) != true)) {
                    this.NumeroEdificiosField = value;
                    this.RaisePropertyChanged("NumeroEdificios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroInmuebles {
            get {
                return this.NumeroInmueblesField;
            }
            set {
                if ((this.NumeroInmueblesField.Equals(value) != true)) {
                    this.NumeroInmueblesField = value;
                    this.RaisePropertyChanged("NumeroInmuebles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Proyecto Proyecto {
            get {
                return this.ProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProyectoField, value) != true)) {
                    this.ProyectoField = value;
                    this.RaisePropertyChanged("Proyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proyecto", Namespace="http://schemas.datacontract.org/2004/07/GestionInmobiliaria.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class Proyecto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CuotaInicialMontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CuotaInicialPorcentajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoMontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoPorcentajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MiViviendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoSeparacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroInmueblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodoEstacionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TechoPropioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anulado {
            get {
                return this.AnuladoField;
            }
            set {
                if ((this.AnuladoField.Equals(value) != true)) {
                    this.AnuladoField = value;
                    this.RaisePropertyChanged("Anulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CuotaInicialMonto {
            get {
                return this.CuotaInicialMontoField;
            }
            set {
                if ((this.CuotaInicialMontoField.Equals(value) != true)) {
                    this.CuotaInicialMontoField = value;
                    this.RaisePropertyChanged("CuotaInicialMonto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CuotaInicialPorcentaje {
            get {
                return this.CuotaInicialPorcentajeField;
            }
            set {
                if ((this.CuotaInicialPorcentajeField.Equals(value) != true)) {
                    this.CuotaInicialPorcentajeField = value;
                    this.RaisePropertyChanged("CuotaInicialPorcentaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DescuentoMonto {
            get {
                return this.DescuentoMontoField;
            }
            set {
                if ((this.DescuentoMontoField.Equals(value) != true)) {
                    this.DescuentoMontoField = value;
                    this.RaisePropertyChanged("DescuentoMonto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DescuentoPorcentaje {
            get {
                return this.DescuentoPorcentajeField;
            }
            set {
                if ((this.DescuentoPorcentajeField.Equals(value) != true)) {
                    this.DescuentoPorcentajeField = value;
                    this.RaisePropertyChanged("DescuentoPorcentaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marcador {
            get {
                return this.MarcadorField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcadorField, value) != true)) {
                    this.MarcadorField = value;
                    this.RaisePropertyChanged("Marcador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MiVivienda {
            get {
                return this.MiViviendaField;
            }
            set {
                if ((this.MiViviendaField.Equals(value) != true)) {
                    this.MiViviendaField = value;
                    this.RaisePropertyChanged("MiVivienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoSeparacion {
            get {
                return this.MontoSeparacionField;
            }
            set {
                if ((this.MontoSeparacionField.Equals(value) != true)) {
                    this.MontoSeparacionField = value;
                    this.RaisePropertyChanged("MontoSeparacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroInmuebles {
            get {
                return this.NumeroInmueblesField;
            }
            set {
                if ((this.NumeroInmueblesField.Equals(value) != true)) {
                    this.NumeroInmueblesField = value;
                    this.RaisePropertyChanged("NumeroInmuebles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodoEstacional {
            get {
                return this.PeriodoEstacionalField;
            }
            set {
                if ((this.PeriodoEstacionalField.Equals(value) != true)) {
                    this.PeriodoEstacionalField = value;
                    this.RaisePropertyChanged("PeriodoEstacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TechoPropio {
            get {
                return this.TechoPropioField;
            }
            set {
                if ((this.TechoPropioField.Equals(value) != true)) {
                    this.TechoPropioField = value;
                    this.RaisePropertyChanged("TechoPropio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoInmueble", Namespace="http://schemas.datacontract.org/2004/07/GestionInmobiliaria.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class TipoInmueble : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProformaWS.IProformaService")]
    public interface IProformaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProformaService/Listar", ReplyAction="http://tempuri.org/IProformaService/ListarResponse")]
        GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Proforma[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProformaService/Agregar", ReplyAction="http://tempuri.org/IProformaService/AgregarResponse")]
        int Agregar(GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Proforma proforma);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProformaServiceChannel : GestionInmobiliaria.SOAPServices.Tests.ProformaWS.IProformaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProformaServiceClient : System.ServiceModel.ClientBase<GestionInmobiliaria.SOAPServices.Tests.ProformaWS.IProformaService>, GestionInmobiliaria.SOAPServices.Tests.ProformaWS.IProformaService {
        
        public ProformaServiceClient() {
        }
        
        public ProformaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProformaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProformaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProformaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Proforma[] Listar() {
            return base.Channel.Listar();
        }
        
        public int Agregar(GestionInmobiliaria.SOAPServices.Tests.ProformaWS.Proforma proforma) {
            return base.Channel.Agregar(proforma);
        }
    }
}
