//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInmobiliaria.SOAPServices.Tests.ProyectoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proyecto", Namespace="http://schemas.datacontract.org/2004/07/GestionInmobiliaria.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class Proyecto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CuotaInicialMontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CuotaInicialPorcentajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoMontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoPorcentajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MiViviendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoSeparacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroInmueblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodoEstacionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TechoPropioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anulado {
            get {
                return this.AnuladoField;
            }
            set {
                if ((this.AnuladoField.Equals(value) != true)) {
                    this.AnuladoField = value;
                    this.RaisePropertyChanged("Anulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CuotaInicialMonto {
            get {
                return this.CuotaInicialMontoField;
            }
            set {
                if ((this.CuotaInicialMontoField.Equals(value) != true)) {
                    this.CuotaInicialMontoField = value;
                    this.RaisePropertyChanged("CuotaInicialMonto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CuotaInicialPorcentaje {
            get {
                return this.CuotaInicialPorcentajeField;
            }
            set {
                if ((this.CuotaInicialPorcentajeField.Equals(value) != true)) {
                    this.CuotaInicialPorcentajeField = value;
                    this.RaisePropertyChanged("CuotaInicialPorcentaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DescuentoMonto {
            get {
                return this.DescuentoMontoField;
            }
            set {
                if ((this.DescuentoMontoField.Equals(value) != true)) {
                    this.DescuentoMontoField = value;
                    this.RaisePropertyChanged("DescuentoMonto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DescuentoPorcentaje {
            get {
                return this.DescuentoPorcentajeField;
            }
            set {
                if ((this.DescuentoPorcentajeField.Equals(value) != true)) {
                    this.DescuentoPorcentajeField = value;
                    this.RaisePropertyChanged("DescuentoPorcentaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marcador {
            get {
                return this.MarcadorField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcadorField, value) != true)) {
                    this.MarcadorField = value;
                    this.RaisePropertyChanged("Marcador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MiVivienda {
            get {
                return this.MiViviendaField;
            }
            set {
                if ((this.MiViviendaField.Equals(value) != true)) {
                    this.MiViviendaField = value;
                    this.RaisePropertyChanged("MiVivienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoSeparacion {
            get {
                return this.MontoSeparacionField;
            }
            set {
                if ((this.MontoSeparacionField.Equals(value) != true)) {
                    this.MontoSeparacionField = value;
                    this.RaisePropertyChanged("MontoSeparacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroInmuebles {
            get {
                return this.NumeroInmueblesField;
            }
            set {
                if ((this.NumeroInmueblesField.Equals(value) != true)) {
                    this.NumeroInmueblesField = value;
                    this.RaisePropertyChanged("NumeroInmuebles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodoEstacional {
            get {
                return this.PeriodoEstacionalField;
            }
            set {
                if ((this.PeriodoEstacionalField.Equals(value) != true)) {
                    this.PeriodoEstacionalField = value;
                    this.RaisePropertyChanged("PeriodoEstacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TechoPropio {
            get {
                return this.TechoPropioField;
            }
            set {
                if ((this.TechoPropioField.Equals(value) != true)) {
                    this.TechoPropioField = value;
                    this.RaisePropertyChanged("TechoPropio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProyectoWS.IProyectoService")]
    public interface IProyectoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Listar", ReplyAction="http://tempuri.org/IProyectoService/ListarResponse")]
        GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.Proyecto[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Obtener", ReplyAction="http://tempuri.org/IProyectoService/ObtenerResponse")]
        GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.Proyecto Obtener(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Agregar", ReplyAction="http://tempuri.org/IProyectoService/AgregarResponse")]
        int Agregar(GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.Proyecto proyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Modificar", ReplyAction="http://tempuri.org/IProyectoService/ModificarResponse")]
        bool Modificar(GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.Proyecto proyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Eliminar", ReplyAction="http://tempuri.org/IProyectoService/EliminarResponse")]
        bool Eliminar(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProyectoServiceChannel : GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.IProyectoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProyectoServiceClient : System.ServiceModel.ClientBase<GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.IProyectoService>, GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.IProyectoService {
        
        public ProyectoServiceClient() {
        }
        
        public ProyectoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProyectoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyectoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyectoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.Proyecto[] Listar() {
            return base.Channel.Listar();
        }
        
        public GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.Proyecto Obtener(int id) {
            return base.Channel.Obtener(id);
        }
        
        public int Agregar(GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.Proyecto proyecto) {
            return base.Channel.Agregar(proyecto);
        }
        
        public bool Modificar(GestionInmobiliaria.SOAPServices.Tests.ProyectoWS.Proyecto proyecto) {
            return base.Channel.Modificar(proyecto);
        }
        
        public bool Eliminar(int id) {
            return base.Channel.Eliminar(id);
        }
    }
}
